# Generated by Django 5.1.6 on 2025-07-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('guardian_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
